// API types — hand-written to mirror `shared/openapi.yaml`. In the real app these
// would be generated by openapi-typescript; here they're maintained alongside the
// mock data so changes stay in one place.

export type UserId = string;
export type GroupId = string;
export type CycleId = string; // "yyyymm"
export type QuestionId = string;
export type ResponseId = string;
export type CommentId = string;
export type ImageId = string;
export type Role = "admin" | "member";
export type CycleStatus = "voting" | "open" | "published" | "archived";
export type QuestionKind = "text" | "poll";

export interface User {
  userId: UserId;
  email: string;
  displayName: string;
  avatarColor: string; // tailwind color slug for the mock
}

export interface Membership {
  groupId: GroupId;
  role: Role;
  groupName: string;
  gradient: GroupGradient;
}

export interface GroupGradient {
  from: string;
  to: string;
  className: string; // matching .hero-* class for visual consistency
}

export interface GroupMember {
  userId: UserId;
  displayName: string;
  role: Role;
  nickname?: string | null;
  avatarColor: string;
  editionsAnswered: number;
  joinedAt: string;
}

export interface Group {
  groupId: GroupId;
  name: string;
  timezone: string;
  cycleSettings: {
    questionsPerCycle: number;
    votesPerUserPerCycle: number;
    responseWindowDays: number;
  };
  notificationSettings: {
    offsetsHoursBeforeClose: number[];
    onCycleOpen: boolean;
  };
  memberSoftCap: number;
  members: GroupMember[];
  gradient: GroupGradient;
}

export interface NewsletterSummary {
  cycleId: CycleId;
  status: CycleStatus;
  responseOpenAt: string;
  responseCloseAt: string;
  publishedAt: string | null;
  questionCount: number;
  myDraftCount: number;
  myPublishedCount: number;
  gradientClass: string;
  monthLabel: string;
  yearLabel: string;
}

export interface PollOption {
  optionId: string;
  label: string;
}

export interface CandidateQuestion {
  questionId: QuestionId;
  kind: QuestionKind;
  prompt: string;
  pollOptions?: PollOption[] | null;
  voteCount: number;
  votedByMe: boolean;
  submittedAt: string;
}

export interface LockedQuestion {
  questionId: QuestionId;
  kind: QuestionKind;
  prompt: string;
  pollOptions?: PollOption[] | null;
  displayOrder: number;
  helperText?: string;
}

export interface ImageMedia {
  imageId: ImageId;
  status: "pending" | "ready" | "failed";
  thumbUrl?: string | null;
  displayUrl?: string | null;
  alt?: string;
  width?: number;
  height?: number;
}

export interface ReactionGroup {
  emoji: string;
  count: number;
  reactedByMe: boolean;
}

export interface Comment {
  commentId: CommentId;
  authorUserId: UserId;
  authorDisplayName: string;
  authorAvatarColor: string;
  body: string;
  createdAt: string;
  editedAt: string | null;
}

export interface AnswerView {
  responseId: ResponseId;
  userId: UserId;
  displayName: string;
  avatarColor: string;
  body: string;
  images: ImageMedia[];
  publishedAt: string;
  comments: Comment[];
  reactionGroups: ReactionGroup[];
}

export interface PublishedTextQuestion extends LockedQuestion {
  kind: "text";
  answers: AnswerView[];
}

export interface PublishedPollQuestion extends LockedQuestion {
  kind: "poll";
  options: (PollOption & { voteCount: number })[];
  totalVotes: number;
  myVoteOptionId: string | null;
}

export type PublishedQuestion = PublishedTextQuestion | PublishedPollQuestion;

export interface MyResponse {
  responseId: ResponseId;
  questionId: QuestionId;
  status: "draft" | "published";
  kind: QuestionKind;
  body?: string;
  imageMediaIds?: string[];
  pollOptionId?: string | null;
  version: number;
  updatedAt: string;
  publishedAt?: string | null;
  wordCount?: number;
}

export interface PublishedNewsletter {
  groupId: GroupId;
  groupName: string;
  cycleId: CycleId;
  status: "published";
  responseCloseAt: string;
  publishedAt: string;
  questions: PublishedQuestion[];
  gradientClass: string;
  monthLabel: string;
  yearLabel: string;
  reactionTotal: number;
}

export interface OpenNewsletter {
  groupId: GroupId;
  groupName: string;
  cycleId: CycleId;
  status: "open";
  responseOpenAt: string;
  responseCloseAt: string;
  questions: LockedQuestion[];
  myResponses: MyResponse[];
  gradientClass: string;
  monthLabel: string;
  yearLabel: string;
  hypeMessage?: string;
}

export interface VotingNewsletter {
  groupId: GroupId;
  groupName: string;
  cycleId: CycleId;
  status: "voting";
  responseOpenAt: string;
  candidates: CandidateQuestion[];
  myVoteCount: number;
  votesPerUserPerCycle: number;
  gradientClass: string;
  monthLabel: string;
  yearLabel: string;
}

export type NewsletterDetail = PublishedNewsletter | OpenNewsletter | VotingNewsletter;

export interface Invite {
  code: string;
  groupId: GroupId;
  groupName: string;
  status: "pending" | "consumed" | "revoked";
  expiresAt: string;
  consumedBy?: string | null;
  consumedAt?: string | null;
  consumedByName?: string | null;
  roleOnRedeem: Role;
}

export interface PushDevice {
  subscriptionId: string;
  userAgent: string;
  icon: string; // emoji for display
  lastSuccessAt: string | null;
}

export interface NotificationPref {
  groupId: GroupId;
  cycleOpen: boolean;
  deadlineReminders: boolean;
}

export interface AppConfig {
  user: User;
  memberships: Membership[];
  vapidPublicKey: string;
  groupDefaults: {
    questionsPerCycle: number;
    votesPerUserPerCycle: number;
    responseWindowDays: number;
    timezone: string;
    autosaveDebounceMs: number;
  };
}
