/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap data the SPA needs after login. */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's bare User profile (no memberships). */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the caller's profile. */
        patch: operations["patchMe"];
        trace?: never;
    };
    "/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an invite for a group. Caller must be an admin of that group. */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/groups/{groupId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invites for a group. Admin only. */
        get: operations["listInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invites/{code}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a pending invite. Idempotent. */
        post: operations["revokeInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an invite code. Covers both first signup (lazily creates the caller's User row) and an existing user joining another group. */
        post: operations["redeemInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's memberships (same join `/config` returns). */
        get: operations["listGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full group detail, including members. Caller must be a member. */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update group settings. Admin only. */
        patch: operations["patchGroup"];
        trace?: never;
    };
    "/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave (self) or kick (admin) a member. The last admin can't leave. */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role. Admin only. */
        patch: operations["patchMember"];
        trace?: never;
    };
    "/groups/{groupId}/newsletters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Past + current + upcoming newsletters for the group, newest first. Caller must be a member. */
        get: operations["listNewsletters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/newsletters/{cycleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The full edition. Shape depends on `status` — see `NewsletterDetailResponse`. `archived` returns 410 instead of a body (`06-newsletter-lifecycle.md` §1; not reachable until archival ships). */
        get: operations["getNewsletter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/candidate-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The candidate pool for the group's next (currently `voting`) cycle. Caller must be a member. */
        get: operations["listCandidateQuestions"];
        put?: never;
        /** Suggest a candidate question for the group's next `voting` cycle. Caller must be a member. */
        post: operations["createCandidateQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/candidate-questions/{questionId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cast an upvote. Idempotent — re-posting returns 200 with the current state. Caller must be a member. */
        post: operations["castCandidateVote"];
        /** Withdraw the caller's upvote. Idempotent. Caller must be a member. */
        delete: operations["withdrawCandidateVote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/groups/{groupId}/candidate-questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a candidate while it's still in `voting` (cascades its votes). Admin only. There is no admin curate/promote surface (`06-newsletter-lifecycle.md` §7). */
        delete: operations["adminDeleteCandidateQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/newsletters/{cycleId}/my-responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's drafts/publishes for this cycle. Caller must be a member. */
        get: operations["listMyResponses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/newsletters/{cycleId}/questions/{questionId}/my-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's draft/published answer to one question. 404 if none exists yet. Caller must be a member. */
        get: operations["getMyResponse"];
        /** Save a draft or publish an answer. Last-write-wins on content — no version tokens, no conflict errors. Publishing is sticky: once published, a later `publish=false` save keeps the new content but cannot unpublish (`03-api-contract.md` §7.3). Caller must be a member. */
        put: operations["saveMyResponse"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. Requires auth, per the idle-backend principle. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "member";
        /** @enum {string} */
        InviteStatus: "pending" | "consumed" | "revoked";
        /**
         * @description Preset group gradient palette slugs. Mirrored in `backend/crates/shared/src/config.rs::GRADIENT_SLUGS` and the frontend palette table; the contract test asserts the two stay identical.
         * @enum {string}
         */
        GradientSlug: "grape-sky" | "ember-rose" | "forest-mint" | "ocean-dusk" | "citrus-blush" | "slate-lilac";
        /**
         * @description Fallback avatar colour slugs. Mirrored in `backend/crates/shared/src/config.rs::AVATAR_COLOR_SLUGS` and the frontend palette table; the contract test asserts the two stay identical.
         * @enum {string}
         */
        AvatarColorSlug: "red" | "orange" | "amber" | "green" | "teal" | "blue" | "violet" | "pink";
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** @description Machine-readable code from the `03-api-contract.md` §1.1 catalog. */
            code: string;
            correlationId: string;
            fieldErrors?: components["schemas"]["FieldError"][];
        };
        MembershipSummary: {
            groupId: string;
            role: components["schemas"]["Role"];
            groupName: string;
        };
        ConfigResponse: {
            userId: string | null;
            email: string | null;
            displayName: string | null;
            vapidPublicKey: string;
            groupDefaults: Record<string, never>;
            memberships: components["schemas"]["MembershipSummary"][];
        };
        UserResponse: {
            userId: string;
            email: string;
            displayName: string;
            avatarColor: components["schemas"]["AvatarColorSlug"];
            avatarMediaId: string | null;
            avatarUrl: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PatchMeRequest: {
            displayName?: string;
            avatarColor?: components["schemas"]["AvatarColorSlug"];
            /** @description Absent leaves the photo alone; an explicit `null` clears it. */
            avatarMediaId?: string | null;
        };
        CreateInviteRequest: {
            groupId: string;
            /** @description Defaults to the group's invite TTL setting when omitted. */
            ttlDays?: number;
            roleOnRedeem: components["schemas"]["Role"];
        };
        CreateInviteResponse: {
            code: string;
            groupId: string;
            /** Format: date-time */
            expiresAt: string;
            roleOnRedeem: components["schemas"]["Role"];
        };
        InviteSummary: {
            code: string;
            groupId: string;
            status: components["schemas"]["InviteStatus"];
            roleOnRedeem: components["schemas"]["Role"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            consumedBy: string | null;
            /** Format: date-time */
            consumedAt: string | null;
        };
        InviteListResponse: {
            items: components["schemas"]["InviteSummary"][];
            nextCursor: string | null;
        };
        RedeemRequest: {
            code: string;
        };
        RedeemResponse: {
            groupId: string;
            groupName: string;
            role: components["schemas"]["Role"];
        };
        MembershipListResponse: {
            memberships: components["schemas"]["MembershipSummary"][];
        };
        MemberResponse: {
            userId: string;
            displayName: string;
            role: components["schemas"]["Role"];
            avatarColor: components["schemas"]["AvatarColorSlug"];
            avatarUrl: string | null;
            /** Format: date-time */
            joinedAt: string;
            editionsAnswered: number;
        };
        CycleSettingsResponse: {
            questionsPerCycle: number;
            votesPerUserPerCycle: number;
            responseWindowDays: number;
        };
        NotificationSettingsResponse: {
            offsetsHoursBeforeClose: number[];
            onCycleOpen: boolean;
        };
        GroupResponse: {
            groupId: string;
            name: string;
            timezone: string;
            gradient: components["schemas"]["GradientSlug"];
            cycleSettings: components["schemas"]["CycleSettingsResponse"];
            notificationSettings: components["schemas"]["NotificationSettingsResponse"];
            memberCount: number;
            memberSoftCap: number;
            /** Format: date-time */
            createdAt: string;
            members: components["schemas"]["MemberResponse"][];
        };
        CycleSettingsPatch: {
            questionsPerCycle?: number;
            votesPerUserPerCycle?: number;
            responseWindowDays?: number;
        };
        NotificationSettingsPatch: {
            offsetsHoursBeforeClose?: number[];
            onCycleOpen?: boolean;
        };
        PatchGroupRequest: {
            name?: string;
            timezone?: string;
            gradient?: components["schemas"]["GradientSlug"];
            cycleSettings?: components["schemas"]["CycleSettingsPatch"];
            notificationSettings?: components["schemas"]["NotificationSettingsPatch"];
            memberSoftCap?: number;
        };
        PatchMemberRequest: {
            role: components["schemas"]["Role"];
        };
        /** @enum {string} */
        QuestionKind: "text" | "poll";
        /** @enum {string} */
        ResponseStatus: "draft" | "published";
        /** @enum {string} */
        NewsletterStatus: "voting" | "open" | "published" | "archived";
        /** @description `null` (at the call site, not here) when `isAnonymous=true` and the caller is neither the submitter nor a group admin. */
        AskedBy: {
            userId: string;
            displayName: string;
            avatarColor: components["schemas"]["AvatarColorSlug"];
            avatarUrl: string | null;
        };
        PollOptionResponse: {
            optionId: string;
            label: string;
        };
        CandidateItemResponse: {
            questionId: string;
            kind: components["schemas"]["QuestionKind"];
            prompt: string;
            pollOptions?: components["schemas"]["PollOptionResponse"][];
            askedBy: components["schemas"]["AskedBy"] | null;
            isAnonymous: boolean;
            voteCount: number;
            votedByMe: boolean;
            /** Format: date-time */
            submittedAt: string;
        };
        CandidateListResponse: {
            nextCycleId: string;
            votesPerUserPerCycle: number;
            myVoteCount: number;
            items: components["schemas"]["CandidateItemResponse"][];
            nextCursor: string | null;
        };
        CreatePollOptionRequest: {
            label: string;
        };
        CreateCandidateRequest: {
            kind: components["schemas"]["QuestionKind"];
            prompt: string;
            pollOptions?: components["schemas"]["CreatePollOptionRequest"][];
            /**
             * @description Fixed at creation; hides `askedBy` from non-admin members when `true`.
             * @default false
             */
            isAnonymous: boolean;
        };
        CandidateVoteResponse: {
            questionId: string;
            voteCount: number;
            votedByMe: boolean;
            myVoteCount: number;
        };
        NewsletterSummary: {
            cycleId: string;
            status: components["schemas"]["NewsletterStatus"];
            /** Format: date-time */
            responseOpenAt: string;
            /** Format: date-time */
            responseCloseAt: string;
            /** Format: date-time */
            publishedAt: string | null;
            questionCount: number;
            myDraftCount: number;
            myPublishedCount: number;
        };
        NewsletterListResponse: {
            items: components["schemas"]["NewsletterSummary"][];
            nextCursor: string | null;
        };
        MyResponseSummary: {
            responseId: string;
            status: components["schemas"]["ResponseStatus"];
            body?: string;
            imageMediaIds: string[];
            pollOptionId?: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        OpenQuestionResponse: {
            questionId: string;
            kind: components["schemas"]["QuestionKind"];
            prompt: string;
            displayOrder: number;
            askedBy: components["schemas"]["AskedBy"] | null;
            isAnonymous: boolean;
            pollOptions?: components["schemas"]["PollOptionResponse"][];
            myResponse: components["schemas"]["MyResponseSummary"] | null;
        };
        PublishedImageResponse: {
            imageId: string;
            displayUrl: string;
            thumbUrl: string;
            width: number;
            height: number;
        };
        PublishedCommentResponse: {
            commentId: string;
            authorUserId: string;
            displayName: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        ReactionGroupResponse: {
            emoji: string;
            count: number;
            reactedByMe: boolean;
        };
        PublishedAnswerResponse: {
            responseId: string;
            userId: string;
            displayName: string;
            body?: string;
            images: components["schemas"]["PublishedImageResponse"][];
            /** Format: date-time */
            publishedAt: string;
            comments: components["schemas"]["PublishedCommentResponse"][];
            reactionGroups: components["schemas"]["ReactionGroupResponse"][];
        };
        PublishedPollOptionResponse: {
            optionId: string;
            label: string;
            voteCount: number;
        };
        /** @description Exactly one of `answers` (text) / `options`+`myVoteOptionId` (poll) is present, matching `kind`. */
        PublishedQuestionResponse: {
            questionId: string;
            kind: components["schemas"]["QuestionKind"];
            prompt: string;
            displayOrder: number;
            askedBy: components["schemas"]["AskedBy"] | null;
            isAnonymous: boolean;
            answers?: components["schemas"]["PublishedAnswerResponse"][];
            options?: components["schemas"]["PublishedPollOptionResponse"][];
            myVoteOptionId?: string;
        };
        /** @description Shape depends on `status`. `archived` is a bare 410, not modeled here. */
        NewsletterDetailResponse: {
            /** @enum {string} */
            status: "voting";
            candidates: components["schemas"]["CandidateItemResponse"][];
        } | {
            /** @enum {string} */
            status: "open";
            cycleId: string;
            /** Format: date-time */
            responseOpenAt: string;
            /** Format: date-time */
            responseCloseAt: string;
            questions: components["schemas"]["OpenQuestionResponse"][];
        } | {
            /** @enum {string} */
            status: "published";
            cycleId: string;
            /** Format: date-time */
            responseCloseAt: string;
            /** Format: date-time */
            publishedAt: string;
            questions: components["schemas"]["PublishedQuestionResponse"][];
        };
        /** @description The full shape of a saved response, returned by every §7 route. */
        ResponseDto: {
            responseId: string;
            userId: string;
            questionId: string;
            groupId: string;
            cycleId: string;
            kind: components["schemas"]["QuestionKind"];
            status: components["schemas"]["ResponseStatus"];
            body?: string;
            pollOptionId?: string;
            imageMediaIds: string[];
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        MyResponsesList: {
            items: components["schemas"]["ResponseDto"][];
        };
        /** @description Tagged by `kind`. Image captions are set separately via `PATCH /uploads/{imageId}` (§9.6), not part of this payload. */
        SaveResponseRequest: {
            /** @enum {string} */
            kind: "text";
            body: string;
            imageMediaIds: string[];
            publish: boolean;
        } | {
            /** @enum {string} */
            kind: "poll";
            pollOptionId: string;
            publish: boolean;
        };
        HealthResponse: {
            status: string;
        };
    };
    responses: {
        /** @description No/invalid JWT. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized for this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource missing or not visible to caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.opennewsletter.example.com/errors/not-found",
                 *       "title": "Not found",
                 *       "status": 404,
                 *       "detail": "group not found",
                 *       "code": "NOT_FOUND",
                 *       "correlationId": "01952f3e-6c1b-7c3a-9d4e-4d5e6f7a8b9c"
                 *     }
                 */
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Body/query failed schema validation; see `fieldErrors`. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.opennewsletter.example.com/errors/validation-failed",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "displayName must be at most 40 characters",
                 *       "code": "VALIDATION_FAILED",
                 *       "correlationId": "01952f3e-6c1b-7c3a-9d4e-4d5e6f7a8b9c",
                 *       "fieldErrors": [
                 *         {
                 *           "field": "displayName",
                 *           "code": "TOO_LONG",
                 *           "message": "displayName must be at most 40 characters"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description State conflict — one of `INVITE_CONSUMED`, `MEMBER_CAP_REACHED`, `LAST_ADMIN`, `VOTE_CAP_REACHED`, `CYCLE_NOT_VOTING`, `CYCLE_NOT_OPEN`, `CYCLE_NOT_PUBLISHED`, `IMAGE_LIMIT_EXCEEDED`, or `CANDIDATE_PROMOTED` (`03-api-contract.md` §1.1). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Invite code is unknown. */
        InviteInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Invite code is past its `expiresAt`. */
        InviteExpired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The cycle has transitioned to `archived` (`NEWSLETTER_ARCHIVED`); see `10-archival.md` for the (deferred) archive-link behavior. */
        NewsletterArchived: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
        GroupIdPath: string;
        /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
        UserIdPath: string;
        /** @example 202606 */
        CycleIdPath: string;
        /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
        QuestionIdPath: string;
        /** @description Filter to newsletters in this status. Omit for all statuses. */
        NewsletterStatusQuery: "voting" | "open" | "published";
        /** @description `top` (default) ranks by vote count; `recent` orders by `submittedAt` descending. */
        CandidateSortQuery: "top" | "recent";
        /** @description Page size, 1-100 (`03-api-contract.md` §1). Some routes cap this lower — see their description. */
        LimitQuery: number;
        /** @description Opaque pagination token from a previous page's `nextCursor`. */
        CursorQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap payload. `userId`/`email`/`displayName` are `null` until the caller redeems their first invite. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": null,
                     *       "email": "quinn@example.com",
                     *       "displayName": "Quinn",
                     *       "vapidPublicKey": "BPV_example_vapid_public_key",
                     *       "groupDefaults": {},
                     *       "memberships": []
                     *     }
                     */
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "email": "quinn@example.com",
                     *       "displayName": "Quinn",
                     *       "avatarColor": "teal",
                     *       "avatarMediaId": null,
                     *       "avatarUrl": null,
                     *       "createdAt": "2026-01-15T18:04:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    patchMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "displayName": "Quinn",
                 *       "avatarColor": "teal",
                 *       "avatarMediaId": null
                 *     }
                 */
                "application/json": components["schemas"]["PatchMeRequest"];
            };
        };
        responses: {
            /** @description The updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "email": "quinn@example.com",
                     *       "displayName": "Quinn",
                     *       "avatarColor": "teal",
                     *       "avatarMediaId": null,
                     *       "avatarUrl": null,
                     *       "createdAt": "2026-01-15T18:04:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                 *       "ttlDays": 7,
                 *       "roleOnRedeem": "member"
                 *     }
                 */
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description The created invite. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ABCD-EFGH-JKMN-PQRS",
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "expiresAt": "2026-02-01T00:00:00Z",
                     *       "roleOnRedeem": "member"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateInviteResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The group's invites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "code": "ABCD-EFGH-JKMN-PQRS",
                     *           "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *           "status": "pending",
                     *           "roleOnRedeem": "member",
                     *           "createdBy": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *           "createdAt": "2026-01-25T00:00:00Z",
                     *           "expiresAt": "2026-02-01T00:00:00Z",
                     *           "consumedBy": null,
                     *           "consumedAt": null
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["InviteListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example ABCD-EFGH-JKMN-PQRS */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked (or already revoked). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    redeemInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "ABCD-EFGH-JKMN-PQRS"
                 *     }
                 */
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description The joined group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "groupName": "Trail Crew",
                     *       "role": "member"
                     *     }
                     */
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            400: components["responses"]["InviteInvalid"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["InviteExpired"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "memberships": [
                     *         {
                     *           "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *           "role": "admin",
                     *           "groupName": "Trail Crew"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["MembershipListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "name": "Trail Crew",
                     *       "timezone": "America/New_York",
                     *       "gradient": "grape-sky",
                     *       "cycleSettings": {
                     *         "questionsPerCycle": 5,
                     *         "votesPerUserPerCycle": 3,
                     *         "responseWindowDays": 4
                     *       },
                     *       "notificationSettings": {
                     *         "offsetsHoursBeforeClose": [
                     *           96,
                     *           48,
                     *           24
                     *         ],
                     *         "onCycleOpen": true
                     *       },
                     *       "memberCount": 1,
                     *       "memberSoftCap": 50,
                     *       "createdAt": "2026-01-01T00:00:00Z",
                     *       "members": [
                     *         {
                     *           "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *           "displayName": "Quinn",
                     *           "role": "admin",
                     *           "avatarColor": "teal",
                     *           "avatarUrl": null,
                     *           "joinedAt": "2026-01-01T00:00:00Z",
                     *           "editionsAnswered": 0
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "gradient": "ocean-dusk",
                 *       "cycleSettings": {
                 *         "questionsPerCycle": 5,
                 *         "votesPerUserPerCycle": 3,
                 *         "responseWindowDays": 4
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PatchGroupRequest"];
            };
        };
        responses: {
            /** @description The updated group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "name": "Trail Crew",
                     *       "timezone": "America/New_York",
                     *       "gradient": "ocean-dusk",
                     *       "cycleSettings": {
                     *         "questionsPerCycle": 5,
                     *         "votesPerUserPerCycle": 3,
                     *         "responseWindowDays": 4
                     *       },
                     *       "notificationSettings": {
                     *         "offsetsHoursBeforeClose": [
                     *           96,
                     *           48,
                     *           24
                     *         ],
                     *         "onCycleOpen": true
                     *       },
                     *       "memberCount": 1,
                     *       "memberSoftCap": 50,
                     *       "createdAt": "2026-01-01T00:00:00Z",
                     *       "members": [
                     *         {
                     *           "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *           "displayName": "Quinn",
                     *           "role": "admin",
                     *           "avatarColor": "teal",
                     *           "avatarUrl": null,
                     *           "joinedAt": "2026-01-01T00:00:00Z",
                     *           "editionsAnswered": 0
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    patchMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "role": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["PatchMemberRequest"];
            };
        };
        responses: {
            /** @description The member's updated profile within the group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "displayName": "Quinn",
                     *       "role": "admin",
                     *       "avatarColor": "teal",
                     *       "avatarUrl": null,
                     *       "joinedAt": "2026-01-01T00:00:00Z",
                     *       "editionsAnswered": 0
                     *     }
                     */
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listNewsletters: {
        parameters: {
            query?: {
                /** @description Filter to newsletters in this status. Omit for all statuses. */
                status?: components["parameters"]["NewsletterStatusQuery"];
                /** @description Page size, 1-100 (`03-api-contract.md` §1). Some routes cap this lower — see their description. */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Opaque pagination token from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["CursorQuery"];
            };
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of newsletters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "cycleId": "202606",
                     *           "status": "open",
                     *           "responseOpenAt": "2026-06-01T00:00:00Z",
                     *           "responseCloseAt": "2026-06-05T00:00:00Z",
                     *           "publishedAt": null,
                     *           "questionCount": 5,
                     *           "myDraftCount": 2,
                     *           "myPublishedCount": 0
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["NewsletterListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getNewsletter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 202606 */
                cycleId: components["parameters"]["CycleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The edition, shaped per its current `status`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "cycleId": "202606",
                     *       "status": "published",
                     *       "responseCloseAt": "2026-06-05T00:00:00Z",
                     *       "publishedAt": "2026-06-05T00:00:01Z",
                     *       "questions": [
                     *         {
                     *           "questionId": "018f2b6b-6c1b-7c3a-9d4e-3c4d5e6f7a8b",
                     *           "kind": "text",
                     *           "prompt": "What's your favorite hike of the year?",
                     *           "displayOrder": 0,
                     *           "askedBy": {
                     *             "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *             "displayName": "Kari",
                     *             "avatarColor": "teal",
                     *             "avatarUrl": null
                     *           },
                     *           "isAnonymous": false,
                     *           "answers": [
                     *             {
                     *               "responseId": "018f2b6b-6c1b-7c3a-9d4e-4d5e6f7a8b9c",
                     *               "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *               "displayName": "Quinn",
                     *               "body": "Lake 22, hands down.",
                     *               "images": [],
                     *               "publishedAt": "2026-06-03T12:00:00Z",
                     *               "comments": [],
                     *               "reactionGroups": [
                     *                 {
                     *                   "emoji": "🔥",
                     *                   "count": 3,
                     *                   "reactedByMe": true
                     *                 }
                     *               ]
                     *             }
                     *           ]
                     *         },
                     *         {
                     *           "questionId": "018f2b6b-6c1b-7c3a-9d4e-5e6f7a8b9c0d",
                     *           "kind": "poll",
                     *           "prompt": "Which trail had the best views?",
                     *           "displayOrder": 1,
                     *           "askedBy": null,
                     *           "isAnonymous": true,
                     *           "options": [
                     *             {
                     *               "optionId": "018f2b6b-6c1b-7c3a-9d4e-6f7a8b9c0d1e",
                     *               "label": "Mt Si",
                     *               "voteCount": 4
                     *             },
                     *             {
                     *               "optionId": "018f2b6b-6c1b-7c3a-9d4e-7a8b9c0d1e2f",
                     *               "label": "Lake 22",
                     *               "voteCount": 7
                     *             }
                     *           ],
                     *           "myVoteOptionId": "018f2b6b-6c1b-7c3a-9d4e-7a8b9c0d1e2f"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["NewsletterDetailResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["NewsletterArchived"];
        };
    };
    listCandidateQuestions: {
        parameters: {
            query?: {
                /** @description `top` (default) ranks by vote count; `recent` orders by `submittedAt` descending. */
                sort?: components["parameters"]["CandidateSortQuery"];
                /** @description Page size, 1-100 (`03-api-contract.md` §1). Some routes cap this lower — see their description. */
                limit?: components["parameters"]["LimitQuery"];
                /** @description Opaque pagination token from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["CursorQuery"];
            };
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate pool. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "nextCycleId": "202606",
                     *       "votesPerUserPerCycle": 3,
                     *       "myVoteCount": 2,
                     *       "items": [
                     *         {
                     *           "questionId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *           "kind": "text",
                     *           "prompt": "What's the best trail you hiked this summer?",
                     *           "askedBy": {
                     *             "userId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *             "displayName": "Kari",
                     *             "avatarColor": "teal",
                     *             "avatarUrl": null
                     *           },
                     *           "isAnonymous": false,
                     *           "voteCount": 7,
                     *           "votedByMe": true,
                     *           "submittedAt": "2026-05-20T00:00:00Z"
                     *         },
                     *         {
                     *           "questionId": "018f2b6b-6c1b-7c3a-9d4e-3c4d5e6f7a8b",
                     *           "kind": "poll",
                     *           "prompt": "Which trailhead should we carpool from?",
                     *           "pollOptions": [
                     *             {
                     *               "optionId": "018f2b6b-6c1b-7c3a-9d4e-4d5e6f7a8b9c",
                     *               "label": "North lot"
                     *             },
                     *             {
                     *               "optionId": "018f2b6b-6c1b-7c3a-9d4e-5e6f7a8b9c0d",
                     *               "label": "South lot"
                     *             }
                     *           ],
                     *           "askedBy": null,
                     *           "isAnonymous": true,
                     *           "voteCount": 5,
                     *           "votedByMe": false,
                     *           "submittedAt": "2026-05-21T00:00:00Z"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["CandidateListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createCandidateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "kind": "text",
                 *       "prompt": "What's your favorite hike of the year?",
                 *       "isAnonymous": false
                 *     }
                 */
                "application/json": components["schemas"]["CreateCandidateRequest"];
            };
        };
        responses: {
            /** @description The created candidate, with `askedBy` populated (the submitter always sees their own attribution). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "questionId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "kind": "text",
                     *       "prompt": "What's your favorite hike of the year?",
                     *       "askedBy": {
                     *         "userId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *         "displayName": "Quinn",
                     *         "avatarColor": "teal",
                     *         "avatarUrl": null
                     *       },
                     *       "isAnonymous": false,
                     *       "voteCount": 0,
                     *       "votedByMe": false,
                     *       "submittedAt": "2026-05-22T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["CandidateItemResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    castCandidateVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                questionId: components["parameters"]["QuestionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate's updated vote state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "questionId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "voteCount": 8,
                     *       "votedByMe": true,
                     *       "myVoteCount": 3
                     *     }
                     */
                    "application/json": components["schemas"]["CandidateVoteResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    withdrawCandidateVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                questionId: components["parameters"]["QuestionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate's updated vote state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "questionId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "voteCount": 7,
                     *       "votedByMe": false,
                     *       "myVoteCount": 2
                     *     }
                     */
                    "application/json": components["schemas"]["CandidateVoteResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminDeleteCandidateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                questionId: components["parameters"]["QuestionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMyResponses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 202606 */
                cycleId: components["parameters"]["CycleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's responses in this cycle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "responseId": "018f2b6b-6c1b-7c3a-9d4e-8b9c0d1e2f3a",
                     *           "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *           "questionId": "018f2b6b-6c1b-7c3a-9d4e-3c4d5e6f7a8b",
                     *           "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *           "cycleId": "202606",
                     *           "kind": "text",
                     *           "status": "draft",
                     *           "body": "Lake 22, hands down.",
                     *           "imageMediaIds": [],
                     *           "updatedAt": "2026-06-02T10:00:00Z",
                     *           "publishedAt": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["MyResponsesList"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["NewsletterArchived"];
        };
    };
    getMyResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 202606 */
                cycleId: components["parameters"]["CycleIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                questionId: components["parameters"]["QuestionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's response to this question. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "responseId": "018f2b6b-6c1b-7c3a-9d4e-8b9c0d1e2f3a",
                     *       "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "questionId": "018f2b6b-6c1b-7c3a-9d4e-3c4d5e6f7a8b",
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "cycleId": "202606",
                     *       "kind": "text",
                     *       "status": "draft",
                     *       "body": "Lake 22, hands down.",
                     *       "imageMediaIds": [],
                     *       "updatedAt": "2026-06-02T10:00:00Z",
                     *       "publishedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["ResponseDto"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["NewsletterArchived"];
        };
    };
    saveMyResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a */
                groupId: components["parameters"]["GroupIdPath"];
                /** @example 202606 */
                cycleId: components["parameters"]["CycleIdPath"];
                /** @example 018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f */
                questionId: components["parameters"]["QuestionIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "kind": "text",
                 *       "body": "Lake 22, hands down.",
                 *       "imageMediaIds": [],
                 *       "publish": false
                 *     }
                 */
                "application/json": components["schemas"]["SaveResponseRequest"];
            };
        };
        responses: {
            /** @description The saved response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "responseId": "018f2b6b-6c1b-7c3a-9d4e-8b9c0d1e2f3a",
                     *       "userId": "018f2b6b-6c1b-7c3a-9d4e-1a2b3c4d5e6f",
                     *       "questionId": "018f2b6b-6c1b-7c3a-9d4e-3c4d5e6f7a8b",
                     *       "groupId": "018f2b6b-6c1b-7c3a-9d4e-2b3c4d5e6f7a",
                     *       "cycleId": "202606",
                     *       "kind": "text",
                     *       "status": "draft",
                     *       "body": "Lake 22, hands down.",
                     *       "imageMediaIds": [],
                     *       "updatedAt": "2026-06-02T10:00:00Z",
                     *       "publishedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["ResponseDto"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["NewsletterArchived"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. `03-api-contract.md` §11.1 also documents `version`/`buildAt` fields, but the handler doesn't emit them yet — see the note on `HealthResponse` in `domain/src/api.rs`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
