#!/usr/bin/env python3
"""Write frontend/.env.{env} from CDK stack outputs.

Reads infra/cdk.out/{env}-outputs.json (produced by 'cdk deploy --outputs-file').
Writes frontend/.env.{env} so Vite picks up the right API/CDN/Cognito endpoints.

Usage:
    python3 scripts/write_frontend_env.py [--env dev]

Called automatically by 'make deploy-dev'.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent


def load_outputs(env: str) -> dict:
    path = REPO_ROOT / "infra" / "cdk.out" / f"{env}-outputs.json"
    if not path.exists():
        sys.exit(
            f"Outputs file not found: {path}\n"
            "Run 'make deploy-dev' first to deploy stacks and generate the file."
        )
    with path.open() as f:
        return json.load(f)


def get(outputs: dict, stack: str, key: str, env: str, fallback: str = "") -> str:
    return outputs.get(f"{stack}-{env}", {}).get(key, fallback)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--env", default="dev")
    args = parser.parse_args()
    env = args.env

    outputs = load_outputs(env)

    user_pool_id = get(outputs, "AuthStack", "UserPoolId", env)
    client_id = get(outputs, "AuthStack", "UserPoolClientId", env)
    bootstrap_client_id = get(outputs, "AuthStack", "UserPoolBootstrapClientId", env)
    cdn_domain = get(outputs, "MediaPersistentStack", "CloudFrontDomain", env)
    # ApiStack lands in M4; fall back to a placeholder so the file is always writable.
    api_endpoint = get(
        outputs,
        "ApiStack",
        "ApiEndpoint",
        env,
        fallback="https://TODO-wire-in-M4.execute-api.us-east-1.amazonaws.com",
    )

    cdn_url = f"https://{cdn_domain}" if cdn_domain else "https://TODO-wire-in-M4.cloudfront.net"

    env_content = (
        "# Auto-generated by scripts/write_frontend_env.py — do not edit manually.\n"
        "# Regenerate with: make deploy-dev\n"
        f"VITE_API_BASE_URL={api_endpoint}\n"
        f"VITE_CDN_BASE_URL={cdn_url}\n"
        f"VITE_COGNITO_USER_POOL_ID={user_pool_id}\n"
        f"VITE_COGNITO_CLIENT_ID={client_id}\n"
        f"VITE_COGNITO_BOOTSTRAP_CLIENT_ID={bootstrap_client_id}\n"
        f"VITE_ENV={env}\n"
    )

    out_path = REPO_ROOT / "frontend" / f".env.{env}"
    out_path.write_text(env_content)
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")

    missing = [k for k, v in {
        "VITE_COGNITO_USER_POOL_ID": user_pool_id,
        "VITE_COGNITO_CLIENT_ID": client_id,
        "VITE_CDN_BASE_URL": cdn_url,
    }.items() if not v or "TODO" in v]
    if missing:
        print(f"  WARNING: missing values for: {', '.join(missing)}")
        print("  Run 'make deploy-dev' to populate them from deployed stacks.")


if __name__ == "__main__":
    main()
